version: '3'

services:
 
  # backend-node:
  #   depends_on:
  #     - database-mysql
  #   container_name: backend-node
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   networks:
  #     - my-node-mysql-network
  #   environment:
  #     - PORT=3000
  #     - JWT_SECRET=test
  #     - ABC=16

  database-mysql:
    container_name: database-mysql
    build: ./database
    ports:
      - "3306:3306"
    # networks:
    #   - my-node-mysql-network
    
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

# networks:
#   my-node-mysql-network:
#     driver: bridge